### ISSUE TITLE
Engine-locations.yml not updated

### ISSUE THREAD

**Issue by aiblis** [diegogarciahuerta/tk-substancepainter#3]
Hello, 
The engine-locations.yml file is not updated on the newer version not loading the proper version of the plugins. 
Also, on the readme documentation the code does not work, it should be like this:

```yml
# substancepainter
engines.tk-substancepainter.location:
  type: git
  path: https://github.com/diegogarciahuerta/tk-substancepainter
  version: v1.1.0
```

Cheers
